# Generated by Django 6.0.3 on 2026-03-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="news_images/")),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
