# Generated by Django 6.0.3 on 2026-03-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
    ]
