# Generated by Django 6.0.3 on 2026-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
