# Generated by Django 6.0.3 on 2026-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Politics", "Politics"),
                    ("Technology", "Technology"),
                    ("Sports", "Sports"),
                    ("Business", "Business"),
                ],
                max_length=50,
            ),
        ),
    ]
