# Generated by Django 6.0.3 on 2026-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_article_views_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
